devtools::use_data_raw()
devtools::use_package("dplyr")
devtools::use_package("xts")
devtools::use_package("tidyselect")
usethis::use_test("select")
usethis::use_test("slice")
usethis::use_mit_license()
